# Generated by Django 3.2.12 on 2022-03-17 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('department', models.CharField(choices=[('Physical Therapy', 'Physical Therapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Speech Therapy', 'Speech Therapy')], default='Physical Therapy', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('firstVisitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.admin')),
                ('assignedTherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.therapist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=40)),
                ('assignedTherapistName', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('firstVisitDate', models.DateField()),
                ('lastVisitDate', models.DateField()),
                ('visitNumber', models.PositiveIntegerField()),
                ('copay', models.PositiveIntegerField()),
                ('treatmentCost', models.PositiveIntegerField()),
                ('therapistFee', models.PositiveIntegerField()),
                ('otherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.admin')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.patient')),
                ('therapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('therapistName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.admin')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.patient')),
                ('therapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.therapist')),
            ],
        ),
    ]
