# Generated by Django 3.2.12 on 2022-03-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='therapist_id',
            new_name='therapist',
        ),
        migrations.RenameField(
            model_name='discharge',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='discharge',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='discharge',
            old_name='therapist_id',
            new_name='therapist',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
