# Generated by Django 3.2.12 on 2022-03-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_auto_20220317_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='discharge',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='discharge',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='discharge',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assignedTherapist',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='admin',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapist_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discharge',
            name='patient_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='therapist_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
