# Generated by Django 3.2.12 on 2022-03-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_auto_20220317_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='department',
            field=models.CharField(choices=[('Physical Therapy', 'Physical Therapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Speech Therapy', 'Speech Therapy')], max_length=50),
        ),
    ]
