# Generated by Django 3.2.12 on 2022-04-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_alter_therapist_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(),
        ),
    ]
