# Generated by Django 3.2.12 on 2022-04-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0006_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discharge',
            old_name='firstVisitDate',
            new_name='registerDate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='firstVisitDate',
            new_name='registerDate',
        ),
    ]
