# Generated by Django 3.2.12 on 2022-04-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0008_auto_20220412_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='lastVisitDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='registerDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registerDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
