# Generated by Django 3.2.12 on 2022-04-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0009_auto_20220418_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(),
        ),
    ]
