# Generated by Django 3.2.12 on 2022-04-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0010_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateTimeField(),
        ),
    ]
