# Generated by Django 3.2.12 on 2022-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0011_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='therapist_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
