# Generated by Django 3.2.12 on 2022-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0012_patient_therapist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='therapist_id',
            new_name='assignedTherapist',
        ),
    ]
