# Generated by Django 3.2.12 on 2022-05-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0013_rename_therapist_id_patient_assignedtherapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='therapistName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='assignedTherapistName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='patientName',
            field=models.CharField(max_length=100),
        ),
    ]
