# Generated by Django 3.2.12 on 2022-05-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0016_discharge_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discharge',
            name='status',
        ),
    ]
