# Generated by Django 3.2.12 on 2022-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0017_remove_discharge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
